//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService_kurs")]
    public interface IService_kurs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/login", ReplyAction="http://tempuri.org/IService_kurs/loginResponse")]
        System.Tuple<string, string, string, string, string> login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/login", ReplyAction="http://tempuri.org/IService_kurs/loginResponse")]
        System.Threading.Tasks.Task<System.Tuple<string, string, string, string, string>> loginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/drop_token", ReplyAction="http://tempuri.org/IService_kurs/drop_tokenResponse")]
        void drop_token(string username, string user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/drop_token", ReplyAction="http://tempuri.org/IService_kurs/drop_tokenResponse")]
        System.Threading.Tasks.Task drop_tokenAsync(string username, string user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/role_bd", ReplyAction="http://tempuri.org/IService_kurs/role_bdResponse")]
        string role_bd(string user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/role_bd", ReplyAction="http://tempuri.org/IService_kurs/role_bdResponse")]
        System.Threading.Tasks.Task<string> role_bdAsync(string user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search", ReplyAction="http://tempuri.org/IService_kurs/searchResponse")]
        string search(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search", ReplyAction="http://tempuri.org/IService_kurs/searchResponse")]
        System.Threading.Tasks.Task<string> searchAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/addpeople", ReplyAction="http://tempuri.org/IService_kurs/addpeopleResponse")]
        void addpeople(string email, string fio, string address, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/addpeople", ReplyAction="http://tempuri.org/IService_kurs/addpeopleResponse")]
        System.Threading.Tasks.Task addpeopleAsync(string email, string fio, string address, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/addpeople_info", ReplyAction="http://tempuri.org/IService_kurs/addpeople_infoResponse")]
        void addpeople_info(string email, System.DateTime d_date, string phone_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/addpeople_info", ReplyAction="http://tempuri.org/IService_kurs/addpeople_infoResponse")]
        System.Threading.Tasks.Task addpeople_infoAsync(string email, System.DateTime d_date, string phone_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/addpeople_info_two", ReplyAction="http://tempuri.org/IService_kurs/addpeople_info_twoResponse")]
        void addpeople_info_two(string email, string card_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/addpeople_info_two", ReplyAction="http://tempuri.org/IService_kurs/addpeople_info_twoResponse")]
        System.Threading.Tasks.Task addpeople_info_twoAsync(string email, string card_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/addpeople_post", ReplyAction="http://tempuri.org/IService_kurs/addpeople_postResponse")]
        void addpeople_post(string email, string post, string salary, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/addpeople_post", ReplyAction="http://tempuri.org/IService_kurs/addpeople_postResponse")]
        System.Threading.Tasks.Task addpeople_postAsync(string email, string post, string salary, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/change_pass", ReplyAction="http://tempuri.org/IService_kurs/change_passResponse")]
        string change_pass(string new_pas, string old_pas, string user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/change_pass", ReplyAction="http://tempuri.org/IService_kurs/change_passResponse")]
        System.Threading.Tasks.Task<string> change_passAsync(string new_pas, string old_pas, string user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/deluser", ReplyAction="http://tempuri.org/IService_kurs/deluserResponse")]
        string deluser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/deluser", ReplyAction="http://tempuri.org/IService_kurs/deluserResponse")]
        System.Threading.Tasks.Task<string> deluserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_people", ReplyAction="http://tempuri.org/IService_kurs/vivod_peopleResponse")]
        System.Data.DataTable vivod_people(int str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_people", ReplyAction="http://tempuri.org/IService_kurs/vivod_peopleResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> vivod_peopleAsync(int str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_staff", ReplyAction="http://tempuri.org/IService_kurs/vivod_staffResponse")]
        System.Data.DataTable vivod_staff(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_staff", ReplyAction="http://tempuri.org/IService_kurs/vivod_staffResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> vivod_staffAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_buyer", ReplyAction="http://tempuri.org/IService_kurs/vivod_buyerResponse")]
        System.Data.DataTable vivod_buyer(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_buyer", ReplyAction="http://tempuri.org/IService_kurs/vivod_buyerResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> vivod_buyerAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_provider", ReplyAction="http://tempuri.org/IService_kurs/vivod_providerResponse")]
        System.Data.DataTable vivod_provider(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_provider", ReplyAction="http://tempuri.org/IService_kurs/vivod_providerResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> vivod_providerAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_admin", ReplyAction="http://tempuri.org/IService_kurs/vivod_adminResponse")]
        System.Data.DataTable vivod_admin(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_admin", ReplyAction="http://tempuri.org/IService_kurs/vivod_adminResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> vivod_adminAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search_fio", ReplyAction="http://tempuri.org/IService_kurs/search_fioResponse")]
        System.Data.DataTable search_fio(string fio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search_fio", ReplyAction="http://tempuri.org/IService_kurs/search_fioResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> search_fioAsync(string fio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search_tovar", ReplyAction="http://tempuri.org/IService_kurs/search_tovarResponse")]
        string search_tovar(string name_tovar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search_tovar", ReplyAction="http://tempuri.org/IService_kurs/search_tovarResponse")]
        System.Threading.Tasks.Task<string> search_tovarAsync(string name_tovar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search_add_tovar", ReplyAction="http://tempuri.org/IService_kurs/search_add_tovarResponse")]
        void search_add_tovar(string name_tovar, string massa_tovar, string price_tovar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search_add_tovar", ReplyAction="http://tempuri.org/IService_kurs/search_add_tovarResponse")]
        System.Threading.Tasks.Task search_add_tovarAsync(string name_tovar, string massa_tovar, string price_tovar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search_add_tovar_on_sklad", ReplyAction="http://tempuri.org/IService_kurs/search_add_tovar_on_skladResponse")]
        void search_add_tovar_on_sklad(string name_tovar, string sklad_name, string count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search_add_tovar_on_sklad", ReplyAction="http://tempuri.org/IService_kurs/search_add_tovar_on_skladResponse")]
        System.Threading.Tasks.Task search_add_tovar_on_skladAsync(string name_tovar, string sklad_name, string count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_tovar", ReplyAction="http://tempuri.org/IService_kurs/vivod_tovarResponse")]
        System.Data.DataTable vivod_tovar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_tovar", ReplyAction="http://tempuri.org/IService_kurs/vivod_tovarResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> vivod_tovarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/searc_tovar_name", ReplyAction="http://tempuri.org/IService_kurs/searc_tovar_nameResponse")]
        System.Data.DataTable searc_tovar_name(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/searc_tovar_name", ReplyAction="http://tempuri.org/IService_kurs/searc_tovar_nameResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> searc_tovar_nameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/drop_tovar_name", ReplyAction="http://tempuri.org/IService_kurs/drop_tovar_nameResponse")]
        void drop_tovar_name(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/drop_tovar_name", ReplyAction="http://tempuri.org/IService_kurs/drop_tovar_nameResponse")]
        System.Threading.Tasks.Task drop_tovar_nameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_ing", ReplyAction="http://tempuri.org/IService_kurs/vivod_ingResponse")]
        System.Data.DataTable vivod_ing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_ing", ReplyAction="http://tempuri.org/IService_kurs/vivod_ingResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> vivod_ingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_tovar_bez", ReplyAction="http://tempuri.org/IService_kurs/vivod_tovar_bezResponse")]
        System.Data.DataTable vivod_tovar_bez();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_tovar_bez", ReplyAction="http://tempuri.org/IService_kurs/vivod_tovar_bezResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> vivod_tovar_bezAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search_ing", ReplyAction="http://tempuri.org/IService_kurs/search_ingResponse")]
        System.Data.DataTable search_ing(string name_ing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search_ing", ReplyAction="http://tempuri.org/IService_kurs/search_ingResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> search_ingAsync(string name_ing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/add_ing", ReplyAction="http://tempuri.org/IService_kurs/add_ingResponse")]
        void add_ing(string name_tovar, string name_ing, string fio, string count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/add_ing", ReplyAction="http://tempuri.org/IService_kurs/add_ingResponse")]
        System.Threading.Tasks.Task add_ingAsync(string name_tovar, string name_ing, string fio, string count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/change_data", ReplyAction="http://tempuri.org/IService_kurs/change_dataResponse")]
        System.Data.DataTable change_data(string user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/change_data", ReplyAction="http://tempuri.org/IService_kurs/change_dataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> change_dataAsync(string user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/update_data", ReplyAction="http://tempuri.org/IService_kurs/update_dataResponse")]
        void update_data(string user_id, string table, string pole, string new_data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/update_data", ReplyAction="http://tempuri.org/IService_kurs/update_dataResponse")]
        System.Threading.Tasks.Task update_dataAsync(string user_id, string table, string pole, string new_data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/update_date", ReplyAction="http://tempuri.org/IService_kurs/update_dateResponse")]
        void update_date(string user_id, System.DateTime date_b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/update_date", ReplyAction="http://tempuri.org/IService_kurs/update_dateResponse")]
        System.Threading.Tasks.Task update_dateAsync(string user_id, System.DateTime date_b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search_sklad", ReplyAction="http://tempuri.org/IService_kurs/search_skladResponse")]
        string search_sklad(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search_sklad", ReplyAction="http://tempuri.org/IService_kurs/search_skladResponse")]
        System.Threading.Tasks.Task<string> search_skladAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search_ing_provider", ReplyAction="http://tempuri.org/IService_kurs/search_ing_providerResponse")]
        string search_ing_provider(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/search_ing_provider", ReplyAction="http://tempuri.org/IService_kurs/search_ing_providerResponse")]
        System.Threading.Tasks.Task<string> search_ing_providerAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_sklad", ReplyAction="http://tempuri.org/IService_kurs/vivod_skladResponse")]
        System.Data.DataTable vivod_sklad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/vivod_sklad", ReplyAction="http://tempuri.org/IService_kurs/vivod_skladResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> vivod_skladAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/add_sklad", ReplyAction="http://tempuri.org/IService_kurs/add_skladResponse")]
        void add_sklad(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/add_sklad", ReplyAction="http://tempuri.org/IService_kurs/add_skladResponse")]
        System.Threading.Tasks.Task add_skladAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/delete_sklad", ReplyAction="http://tempuri.org/IService_kurs/delete_skladResponse")]
        void delete_sklad(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/delete_sklad", ReplyAction="http://tempuri.org/IService_kurs/delete_skladResponse")]
        System.Threading.Tasks.Task delete_skladAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/drop_ing", ReplyAction="http://tempuri.org/IService_kurs/drop_ingResponse")]
        string drop_ing(string name, string fio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_kurs/drop_ing", ReplyAction="http://tempuri.org/IService_kurs/drop_ingResponse")]
        System.Threading.Tasks.Task<string> drop_ingAsync(string name, string fio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_kursChannel : Client.ServiceReference.IService_kurs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_kursClient : System.ServiceModel.ClientBase<Client.ServiceReference.IService_kurs>, Client.ServiceReference.IService_kurs {
        
        public Service_kursClient() {
        }
        
        public Service_kursClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_kursClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_kursClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_kursClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Tuple<string, string, string, string, string> login(string username, string password) {
            return base.Channel.login(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<string, string, string, string, string>> loginAsync(string username, string password) {
            return base.Channel.loginAsync(username, password);
        }
        
        public void drop_token(string username, string user_id) {
            base.Channel.drop_token(username, user_id);
        }
        
        public System.Threading.Tasks.Task drop_tokenAsync(string username, string user_id) {
            return base.Channel.drop_tokenAsync(username, user_id);
        }
        
        public string role_bd(string user_id) {
            return base.Channel.role_bd(user_id);
        }
        
        public System.Threading.Tasks.Task<string> role_bdAsync(string user_id) {
            return base.Channel.role_bdAsync(user_id);
        }
        
        public string search(string email) {
            return base.Channel.search(email);
        }
        
        public System.Threading.Tasks.Task<string> searchAsync(string email) {
            return base.Channel.searchAsync(email);
        }
        
        public void addpeople(string email, string fio, string address, string role) {
            base.Channel.addpeople(email, fio, address, role);
        }
        
        public System.Threading.Tasks.Task addpeopleAsync(string email, string fio, string address, string role) {
            return base.Channel.addpeopleAsync(email, fio, address, role);
        }
        
        public void addpeople_info(string email, System.DateTime d_date, string phone_number) {
            base.Channel.addpeople_info(email, d_date, phone_number);
        }
        
        public System.Threading.Tasks.Task addpeople_infoAsync(string email, System.DateTime d_date, string phone_number) {
            return base.Channel.addpeople_infoAsync(email, d_date, phone_number);
        }
        
        public void addpeople_info_two(string email, string card_number) {
            base.Channel.addpeople_info_two(email, card_number);
        }
        
        public System.Threading.Tasks.Task addpeople_info_twoAsync(string email, string card_number) {
            return base.Channel.addpeople_info_twoAsync(email, card_number);
        }
        
        public void addpeople_post(string email, string post, string salary, string role) {
            base.Channel.addpeople_post(email, post, salary, role);
        }
        
        public System.Threading.Tasks.Task addpeople_postAsync(string email, string post, string salary, string role) {
            return base.Channel.addpeople_postAsync(email, post, salary, role);
        }
        
        public string change_pass(string new_pas, string old_pas, string user_id) {
            return base.Channel.change_pass(new_pas, old_pas, user_id);
        }
        
        public System.Threading.Tasks.Task<string> change_passAsync(string new_pas, string old_pas, string user_id) {
            return base.Channel.change_passAsync(new_pas, old_pas, user_id);
        }
        
        public string deluser(string username) {
            return base.Channel.deluser(username);
        }
        
        public System.Threading.Tasks.Task<string> deluserAsync(string username) {
            return base.Channel.deluserAsync(username);
        }
        
        public System.Data.DataTable vivod_people(int str) {
            return base.Channel.vivod_people(str);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> vivod_peopleAsync(int str) {
            return base.Channel.vivod_peopleAsync(str);
        }
        
        public System.Data.DataTable vivod_staff(string id) {
            return base.Channel.vivod_staff(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> vivod_staffAsync(string id) {
            return base.Channel.vivod_staffAsync(id);
        }
        
        public System.Data.DataTable vivod_buyer(string id) {
            return base.Channel.vivod_buyer(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> vivod_buyerAsync(string id) {
            return base.Channel.vivod_buyerAsync(id);
        }
        
        public System.Data.DataTable vivod_provider(string id) {
            return base.Channel.vivod_provider(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> vivod_providerAsync(string id) {
            return base.Channel.vivod_providerAsync(id);
        }
        
        public System.Data.DataTable vivod_admin(string id) {
            return base.Channel.vivod_admin(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> vivod_adminAsync(string id) {
            return base.Channel.vivod_adminAsync(id);
        }
        
        public System.Data.DataTable search_fio(string fio) {
            return base.Channel.search_fio(fio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> search_fioAsync(string fio) {
            return base.Channel.search_fioAsync(fio);
        }
        
        public string search_tovar(string name_tovar) {
            return base.Channel.search_tovar(name_tovar);
        }
        
        public System.Threading.Tasks.Task<string> search_tovarAsync(string name_tovar) {
            return base.Channel.search_tovarAsync(name_tovar);
        }
        
        public void search_add_tovar(string name_tovar, string massa_tovar, string price_tovar) {
            base.Channel.search_add_tovar(name_tovar, massa_tovar, price_tovar);
        }
        
        public System.Threading.Tasks.Task search_add_tovarAsync(string name_tovar, string massa_tovar, string price_tovar) {
            return base.Channel.search_add_tovarAsync(name_tovar, massa_tovar, price_tovar);
        }
        
        public void search_add_tovar_on_sklad(string name_tovar, string sklad_name, string count) {
            base.Channel.search_add_tovar_on_sklad(name_tovar, sklad_name, count);
        }
        
        public System.Threading.Tasks.Task search_add_tovar_on_skladAsync(string name_tovar, string sklad_name, string count) {
            return base.Channel.search_add_tovar_on_skladAsync(name_tovar, sklad_name, count);
        }
        
        public System.Data.DataTable vivod_tovar() {
            return base.Channel.vivod_tovar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> vivod_tovarAsync() {
            return base.Channel.vivod_tovarAsync();
        }
        
        public System.Data.DataTable searc_tovar_name(string name) {
            return base.Channel.searc_tovar_name(name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> searc_tovar_nameAsync(string name) {
            return base.Channel.searc_tovar_nameAsync(name);
        }
        
        public void drop_tovar_name(string name) {
            base.Channel.drop_tovar_name(name);
        }
        
        public System.Threading.Tasks.Task drop_tovar_nameAsync(string name) {
            return base.Channel.drop_tovar_nameAsync(name);
        }
        
        public System.Data.DataTable vivod_ing() {
            return base.Channel.vivod_ing();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> vivod_ingAsync() {
            return base.Channel.vivod_ingAsync();
        }
        
        public System.Data.DataTable vivod_tovar_bez() {
            return base.Channel.vivod_tovar_bez();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> vivod_tovar_bezAsync() {
            return base.Channel.vivod_tovar_bezAsync();
        }
        
        public System.Data.DataTable search_ing(string name_ing) {
            return base.Channel.search_ing(name_ing);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> search_ingAsync(string name_ing) {
            return base.Channel.search_ingAsync(name_ing);
        }
        
        public void add_ing(string name_tovar, string name_ing, string fio, string count) {
            base.Channel.add_ing(name_tovar, name_ing, fio, count);
        }
        
        public System.Threading.Tasks.Task add_ingAsync(string name_tovar, string name_ing, string fio, string count) {
            return base.Channel.add_ingAsync(name_tovar, name_ing, fio, count);
        }
        
        public System.Data.DataTable change_data(string user_id) {
            return base.Channel.change_data(user_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> change_dataAsync(string user_id) {
            return base.Channel.change_dataAsync(user_id);
        }
        
        public void update_data(string user_id, string table, string pole, string new_data) {
            base.Channel.update_data(user_id, table, pole, new_data);
        }
        
        public System.Threading.Tasks.Task update_dataAsync(string user_id, string table, string pole, string new_data) {
            return base.Channel.update_dataAsync(user_id, table, pole, new_data);
        }
        
        public void update_date(string user_id, System.DateTime date_b) {
            base.Channel.update_date(user_id, date_b);
        }
        
        public System.Threading.Tasks.Task update_dateAsync(string user_id, System.DateTime date_b) {
            return base.Channel.update_dateAsync(user_id, date_b);
        }
        
        public string search_sklad(string name) {
            return base.Channel.search_sklad(name);
        }
        
        public System.Threading.Tasks.Task<string> search_skladAsync(string name) {
            return base.Channel.search_skladAsync(name);
        }
        
        public string search_ing_provider(string name) {
            return base.Channel.search_ing_provider(name);
        }
        
        public System.Threading.Tasks.Task<string> search_ing_providerAsync(string name) {
            return base.Channel.search_ing_providerAsync(name);
        }
        
        public System.Data.DataTable vivod_sklad() {
            return base.Channel.vivod_sklad();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> vivod_skladAsync() {
            return base.Channel.vivod_skladAsync();
        }
        
        public void add_sklad(string name) {
            base.Channel.add_sklad(name);
        }
        
        public System.Threading.Tasks.Task add_skladAsync(string name) {
            return base.Channel.add_skladAsync(name);
        }
        
        public void delete_sklad(string name) {
            base.Channel.delete_sklad(name);
        }
        
        public System.Threading.Tasks.Task delete_skladAsync(string name) {
            return base.Channel.delete_skladAsync(name);
        }
        
        public string drop_ing(string name, string fio) {
            return base.Channel.drop_ing(name, fio);
        }
        
        public System.Threading.Tasks.Task<string> drop_ingAsync(string name, string fio) {
            return base.Channel.drop_ingAsync(name, fio);
        }
    }
}
